# Generated by Django 5.0.3 on 2024-04-03 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteurs', models.CharField(max_length=255)),
                ('editeur', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('genre', models.CharField(max_length=255)),
                ('langue', models.CharField(max_length=2)),
                ('resume', models.TextField(blank=True, null=True)),
                ('disponibilite', models.CharField(max_length=20)),
                ('emplacement', models.CharField(blank=True, max_length=255, null=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='frontend/public/books/')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('abime', 'Abîmé')], max_length=20)),
                ('code_barres', models.CharField(max_length=255)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livre')),
            ],
        ),
        migrations.CreateModel(
            name='LivreCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categorie')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livre')),
            ],
        ),
        migrations.CreateModel(
            name='LivreGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genre')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], max_length=20)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
