# Generated by Django 5.0.3 on 2024-03-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Book',
        ),
    ]
