# Generated by Django 5.0.3 on 2024-03-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
