# Generated by Django 5.0.3 on 2024-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categorie_genre_livre_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/public/books/'),
        ),
    ]
